### ISSUE TITLE
Chrome バージョン130.0.6723.70で動作しない

### ISSUE THREAD

**Issue by takaseakira** [xmitoux/naildcard#19]
Chrome バージョン130.0.6723.70で以下のようなエラーが出て、novelai.net/imageのWebページで生成ボタンの横に🎲が表示されず正常に動作していません。

Refused to load the script 'chrome-extension://f3cb2b03-b9a7-453b-8799-379f5c0450d1/assets/content.ts-rDvgxUHI.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

スタックトレースで
assets/content.ts-loader-pJ_1P3MX.js:8 (無名関数)
8行目
      chrome.runtime.getURL("assets/content.ts-rDvgxUHI.js")
がハイライトされています。

修正可能でしょうか？
よろしくお願いします

**Comment by xmitoux** [comment]
@takaseakira 
ご報告ありがとうございます！
 ご指摘いただいた問題を修正したバージョンをリリースしました。
https://github.com/xmitoux/naildcard/releases/tag/v1.4.1

**Comment by takaseakira** [comment]
対応ありがとうございます
動作確認できました

**Comment by Leonard-the-aromantic** [comment]
同じ症状で困っていました。
迅速なご対応ありがとうございます。
